### ISSUE TITLE
Some enums are not being parsed at all

### ISSUE THREAD

**Issue by tinder-tannerbennett** [Swiftify-Corp/Swiftify#238] opened 2023-04-27 23:22 UTC
Given some code like this:

```objc
NS_ASSUME_NONNULL_BEGIN

@class TNDRTutorial, MKPlacemark, CLPlacemark, CLLocation;

// TNDRAnalyticsTrackerTypes
typedef NS_ENUM(NSInteger, TNDRRecsBlend) { };
```

Swiftify gives the following errors:

```
TNDRCurrentUser.h: (21:44) No viable alternative at input 'typedef NS_ENUM(NSInteger, TNDRRecsBlend) { }'
TNDRCurrentUser.h: (21:45) Extraneous input ';'
```

We are getting similar errors with `NS_CLOSED_ENUM` like so:
```objc
typedef NS_CLOSED_ENUM(NSInteger, TNDRRecsBlend);
```

and changing it to a regular `NS_ENUM` hasn't helped. The rest of the errors surrounding enums all say:
```objc
Unable to convert: 'typedef'
```

**Comment by alex-swiftify** [comment] 2023-04-28 07:52
Thanks, @tinder-tannerbennett for reporting.
We'll address it ASAP and get back to you.

**Comment by alex-swiftify** [comment] 2023-04-28 12:33
@tinder-tannerbennett 
1) For your first code sample:
`typedef NS_ENUM(NSInteger, TNDRRecsBlend) { };`
the original Objective-C code doesn't compile in Xcode, producing a "Use of empty enum" error:
https://take.ms/ToVr3

2) The second sample without `{}` block:
`typedef NS_CLOSED_ENUM(NSInteger, TNDRRecsBlend);`
compiles in Xcode successfully.

The converter issues were caused by the fact that the enum contains no cases, it's fixed now.

However, I wanted your advice on how we should convert such cases.

1) The first sample could be converted to
```
enum TNDRRecsBlend : Int {
}
```
which [won't compile in Xcode](https://take.ms/wsADj) either.

2) The second code sample could be converted to an empty code (if it's meant to be a "forward declaration"),
or an empty enum declaration without specifying the base type, so that it compiles successfully: 
```
enum TNDRRecsBlend /*: Int*/ {
}
```

**Comment by tinder-tannerbennett** [comment] 2023-04-28 17:49
To elaborate on our use case, we apparently use empty closed enums to forward-declare enums defined in a separate header file

**Comment by alex-swiftify** [comment] 2023-04-28 21:17
@tinder-tannerbennett 
Thanks for the clarification. 
The Offline version is expected to be updated next week. 
I’ll update you when it happens.

**Comment by alex-swiftify** [comment] 2023-05-02 14:02
Hi @tinder-tannerbennett,
Can you please clarify the following, for the long-term solution:
1) Do you need to support this syntax with an empty block but no enum cases (although that doesn’t compile in Xcode)?
`typedef NS_ENUM(NSInteger, TNDRRecsBlend) { }; `
2) Are you fine if we convert such forward declarations to such commented declarations?
`// enum TNDRRecsBlend { } `

Thanks in advance!

**Comment by alex-swiftify** [comment] 2023-05-05 12:17
@tinder-tannerbennett Just FYI, the updated version 5.8.1 of the Offline Converter including this issue fixed, as soon as other important bug fixes have been released.

You will receive the new version via automatic updates built into the app, or you can always download it [from our website](https://swiftify.com/offline-converter/).

This issue has been fixed as suggested in my above comment.
Furthermore, forward enum declarations are completely skipped if the full definition of the same enum is included in the same conversion.

If you have anything to add here, you are welcome.

**Closed by alex-swiftify** 2023-05-05 12:17 UTC
