### ISSUE TITLE
Getting framework project version in Swift

### ISSUE THREAD

**Issue by Ibrahimhass** [Swiftify-Corp/Swiftify#173] opened 2021-06-25 17:30 UTC
https://swiftify.me/ntrwyq/1
**Original Objective-C code**

`FOUNDATION_EXPORT const unsigned char YIInnerShadowViewVersionString[];`

**Converted Swift Code**
`let YIInnerShadowViewVersionString = [UInt8](repeating: 0, count: )`

**Suggested Conversion**
```
//https://stackoverflow.com/a/31418789/
let bundle = Bundle(identifier: "com.inamiy.YIInnerShadowView")!
let YIInnerShadowViewVersionString = bundle.infoDictionary![kCFBundleVersionKey as String] as? String

```

**Comment by alex-swiftify** [comment] 2021-07-29 13:48
@Ibrahimhass After some research, I confirmed that `FOUNDATION_EXPORT`  is just very similar to `extern` keyword.
Indeed,  `FOUNDATION_EXPORT` is commonly used to access the library version number, which is declared in the (Xcode generated) "umbrella header".
However, `FOUNDATION_EXPORT` by itself only marks the global variable available to the external C/C++ code, thus we can't assume that such a variable contains the version number.

Sources:
https://developpaper.com/understanding-and-usage-of-ios-common-macros/
https://stackoverflow.com/a/539191/1531236

I thought about using your suggestion only if the variable name contains "VersionNumber" or "VersionString", but the problem is that we cannot reliably know the referred bundle name (and using CFBundleGetMainBundle() would not be always correct).

Thus I'll fix the output code to something that compiles, i.e.
```
let CommonVersionString: [UInt8] = []
```
and close this out.

**Comment by alex-swiftify** [comment] 2021-07-29 14:04
Fixed. Converter output:
```
let YIInnerShadowViewVersionString: [UInt8] = []
```

**Closed by alex-swiftify** 2021-07-29 14:04 UTC
