### ISSUE TITLE
Strange naming in conversion

### ISSUE THREAD

**Issue by AlexanderJ** [Swiftify-Corp/Swiftify#210] opened 2022-03-16 07:45 UTC
If I use this as input
```
@implementation NSDate (Additions)

- (NSString*)shortTimeString
{
	return [self stringWithDateStyle:NSDateFormatterNoStyle timeStyle:NSDateFormatterShortStyle];
}

- (NSString*)shortDateString
{
	return [self stringWithDateStyle:NSDateFormatterShortStyle timeStyle:NSDateFormatterNoStyle];
}

- (NSString*)mediumDateTimeString
{
	return [self stringWithDateStyle:NSDateFormatterMediumStyle timeStyle:NSDateFormatterMediumStyle];
}

- (NSString*)mediumTimeString
{
	return [self stringWithDateStyle:NSDateFormatterNoStyle timeStyle:NSDateFormatterMediumStyle];
}

- (NSString*)mediumDateString
{
	return [self stringWithDateStyle:NSDateFormatterMediumStyle timeStyle:NSDateFormatterNoStyle];
}

- (NSString*)longDateTimeString
{
	return [self stringWithDateStyle:NSDateFormatterLongStyle timeStyle:NSDateFormatterLongStyle];
}

- (NSString*)longTimeString
{
	return [self stringWithDateStyle:NSDateFormatterNoStyle timeStyle:NSDateFormatterLongStyle];
}

- (NSString*)longDateString
{
	return [self stringWithDateStyle:NSDateFormatterLongStyle timeStyle:NSDateFormatterNoStyle];
}

- (NSString*)longDateShortTimeString
{
	return [self stringWithDateStyle:NSDateFormatterLongStyle timeStyle:NSDateFormatterShortStyle];
}

@end
```

I get this output. Sometimes the "Date" is removed from the method name and sometimes its not. I think the pattern here is that longDate is changed to date, but every other prefix before Date does not remove Date. In this concrete case it should never be removed. However, there are cases where this would make sense from the Swift naming scheme. So maybe in doubt there needs to be some kind of interactivity here or at least the original name needs to be added as a comment to easily clean this up afterwards.

```
//  Converted to Swift 5.5 by Swiftify v5.5.24623 - https://swiftify.com/
extension Date {
    func shortTimeString() -> String? {
        return string(withDateStyle: DateFormatter.Style.none, time: DateFormatter.Style.short)
    }

    func shortDateString() -> String? {
        return string(withDateStyle: DateFormatter.Style.short, time: DateFormatter.Style.none)
    }

    func mediumDateTimeString() -> String? {
        return string(withDateStyle: DateFormatter.Style.medium, time: DateFormatter.Style.medium)
    }

    func mediumTimeString() -> String? {
        return string(withDateStyle: DateFormatter.Style.none, time: DateFormatter.Style.medium)
    }

    func mediumDateString() -> String? {
        return string(withDateStyle: DateFormatter.Style.medium, time: DateFormatter.Style.none)
    }

    func longTimeString() -> String? {
        return string(withDateStyle: DateFormatter.Style.long, time: DateFormatter.Style.long)
    }

    func longTimeString() -> String? {
        return string(withDateStyle: DateFormatter.Style.none, time: DateFormatter.Style.long)
    }

    func longString() -> String? {
        return string(withDateStyle: DateFormatter.Style.long, time: DateFormatter.Style.none)
    }

    func longShortTimeString() -> String? {
        return string(withDateStyle: DateFormatter.Style.long, time: DateFormatter.Style.short)
    }
}
```

`longString` should be `longDateString` and `longShortTimeString` should be `longDateShortTimeString`

**Comment by alex-swiftify** [comment] 2022-03-16 12:19
@AlexanderJ This "feature" was introduced in Swift 3 and called "[omit needless words](https://github.com/apple/swift/blob/main/docs/CToSwiftNameTranslation-OmitNeedlessWords.md)".
We are following the same algorithm as Apple to omit needless words.

I've just tested and confirmed that Xcode's "Generated Interface" also produces the function named `longString` for your case: https://take.ms/we0uL

While our current behavior allows the generated code to be compatible with the existing Objective-C code (imported by Xcode) when migrating a project gradually, I agree that there are cases when this may not be desirable.

I have added your case to https://swiftify.atlassian.net/browse/SWC-441 and we will consider making this behavior configurable.

As regarding adding a comment with the original name, I think adding an `@objc` attribute would be the most appropriate choice -
https://swiftify.atlassian.net/browse/SWC-219
However, since these changes affect a lot of method names, at most we could make this behavior configurable, rather than enabled by default.

I'm closing this task in favor of the 2 mentioned Jira issues, but don't hesitate to add any comments here.

**Closed by alex-swiftify** 2022-03-16 12:19 UTC
