### ISSUE TITLE
Error parameter is stripped

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#41] opened 2019-03-13 21:10 UTC
Methods that take an `NSError` as a parameter should be wrapped in a `do ... catch` block, instead of simply ditching the error parameter.
http://swiftify.me/6ox5al

**Comment by alex-swiftify** [comment] 2019-03-14 14:27
JIRA issue: SWC-870 Methods that take an NSError as a parameter should be wrapped in a `do..catch` block

**Comment by nickasd** [comment] 2019-03-14 17:21
Another example: a method with an `NSError` parameter is converted to a method without that parameter and the keyword `throws`, but all the internal calls that use the error parameter are still marked with `try?` instead of `try`.
http://swiftify.me/xj3soc

**Comment by alex-swiftify** [comment] 2019-04-01 15:45
@nickasd In your opinion, should we 
(1) always generate `try` expressions (and wrap them into `do..catch` blocks if the enclosing method is not marked as `throws`, or
(2) generate `try` expressions only if the error variable is used elsewhere in the code; otherwise, generate `try?` expressions?

**Comment by nickasd** [comment] 2019-04-01 16:14
I would say if the error parameter given to the caller is the same as the one passed to the callee (which would also be marked as `throws`), then use `try`, otherwise if the `error` parameter is given generate `do..catch`, otherwise generate `try?`.

**Comment by alex-swiftify** [comment] 2019-04-02 14:15
@nickasd As I understand, you are suggesting to keep generating `try?` statement(s) if `NULL` is passed as the error parameter.
I agree this is probably the best solution, however, this requires us to handle way more nullability scenarios (i.e. support for unwrapping expressions including `try` vs `try?` statements, different result type in these cases, etc) which looks like a huge complication of the codebase.

Do you think if we never generate `try?` expressions and always generate `try` (plus do/catch block if needed), that would be still an acceptable solution?

**Comment by nickasd** [comment] 2019-04-02 14:20
I'm not sure I understand. Is this not what you suggested in (2)?

**Comment by alex-swiftify** [comment] 2019-04-02 14:30
No, it's rather what I suggested in (1) above.

Same time, I agree that it is very difficult to handle the translation of http://swiftify.me/7gfww6/1 from #31 using a `try` expression (so `try?` is yet a better fit for nested expressions).

**Comment by nickasd** [comment] 2019-04-02 15:56
I mean that your point (2) is contained in my suggestion, so I don't see why it is now a problem.

**Comment by alex-swiftify** [comment] 2019-04-02 16:32
As I've explained, the problem is that it appears too difficult to maintain support for both `try` and `try?` statements, including all the consequences.
That was one of the options I have initially suggested, but further research reveals that this multiplies the development efforts, further texting, and support.
I'm researching the possibility to use `try` expressions only for most cases.

For complex expressions like http://swiftify.me/7gfww6/2 we will still need to either
(1) break the complex expression, moving the `try` statement outside of the 
(2) use `try?` expressions.

**Comment by nickasd** [comment] 2019-04-02 20:22
I agree that it is not easy considering all the different cases. I think you could start doing what you think is a more general solution that is also not too complex to implement, and then possibly look into optimizing some standard use cases.

**Comment by alex-swiftify** [comment] 2019-04-04 15:20
Output after the changes (not yet released):

1) http://swiftify.me/6ox5al
```
var error: Error?
        var tags: [Any]
        let url: URL?
        do {
            try (url as NSURL?)?.getResourceValue(&tags, forKey: .tagNamesKey)
        } catch {
        }
```

2) http://swiftify.me/xj3soc
```
    func setValue(_ value: String?) throws {
        try FileManager.default().contentsOfDirectory(at: nil, includingPropertiesForKeys: nil, options: [])
        return true
    }
```

3) The only case when a `try?` statement is generated is when:
* the result of the method call is returned
* the parent method is not declared as `throws`.

Objective: when the `return` keyword is used in Objective-C, it is clear that the error variable is not used below, and adding a `do...catch` block that returns `nil` from the `catch` clause is just more messy than simply changing the `try` statement to `try?`.

Sample input:
```
@interface NSData (JSON)
@property(nonatomic, readonly) id JSONObject;
@end
@implementation NSData (JSON)
- (id)JSONObject {
    return [NSJSONSerialization JSONObjectWithData:self
                                           options:NSJSONReadingAllowFragments
                                             error:nil];
}
@end
```

Output:
```
extension Data {
    var jsonObject: Any? {
        return try? JSONSerialization.jsonObject(with: self as Data, options: .allowFragments)
    }
}
```

**Closed by alex-swiftify** 2019-04-04 15:20 UTC
